spring:
  application:
    name: motorbike-service
  cloud:
    config:
      enabled: true
      uri: http://localhost:8080			
server:
  port: 0   # arranca en un puerto aleatorio hasta que obtenga config rea